import * as WEBIFC from "web-ifc";

export const BUILDING_ELEMENT_TYPES = [
  // Structural elements
  WEBIFC.IFCWALL,
  WEBIFC.IFCWALLSTANDARDCASE,
  WEBIFC.IFCSLAB,
  WEBIFC.IFCSLABSTANDARDCASE,
  WEBIFC.IFCBEAM,
  WEBIFC.IFCBEAMSTANDARDCASE,
  WEBIFC.IFCCOLUMN,
  WEBIFC.IFCCOLUMNSTANDARDCASE,
  WEBIFC.IFCFOOTING,
  WEBIFC.IFCPILE,

  // Openings
  WEBIFC.IFCDOOR,
  WEBIFC.IFCDOORSTANDARDCASE,
  WEBIFC.IFCWINDOW,
  WEBIFC.IFCWINDOWSTANDARDCASE,
  WEBIFC.IFCOPENINGELEMENT,
  WEBIFC.IFCOPENINGSTANDARDCASE,

  // Building services
  WEBIFC.IFCDUCTSEGMENT,
  WEBIFC.IFCDUCTFITTING,
  WEBIFC.IFCPIPESEGMENT,
  WEBIFC.IFCPIPEFITTING,
  WEBIFC.IFCAIRTERMINAL,
  WEBIFC.IFCDISTRIBUTIONPORT,

  // Architectural elements
  WEBIFC.IFCSTAIR,
  WEBIFC.IFCSTAIRFLIGHT,
  WEBIFC.IFCRAMP,
  WEBIFC.IFCRAMPFLIGHT,
  WEBIFC.IFCRAILING,
  WEBIFC.IFCROOF,
  WEBIFC.IFCCURTAINWALL,
  WEBIFC.IFCMEMBER,
  WEBIFC.IFCPLATE,
  WEBIFC.IFCCOVERING,

  // Furniture and equipment
  WEBIFC.IFCFURNISHINGELEMENT,
  WEBIFC.IFCFURNITURE,
  WEBIFC.IFCSYSTEMFURNITUREELEMENT,
  WEBIFC.IFCEQUIPMENTELEMENT,

  // Special elements
  WEBIFC.IFCBUILDINGELEMENTPROXY,
  WEBIFC.IFCBUILDINGELEMENTPART,
  WEBIFC.IFCVIRTUALELEMENT,
  WEBIFC.IFCTRANSPORTELEMENT,

  // IFC4 additions
  WEBIFC.IFCCHIMNEY,
  WEBIFC.IFCSHADINGDEVICE,
  WEBIFC.IFCSOLARDEVICE,
];
